# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "chad-thompson-VAGRANTSLASH-ubuntu-trusty64-gui"
  config.vm.synced_folder "shared", "/tmp/shared"

  config.vm.provider "virtualbox" do |vb|
  	vb.memory="4096"
  	vb.cpus=2
  end
  config.vm.define "PagentOS" do |agentOS|
	  agentOS.vm.hostname="agentPawanAnsible.qac.local"
	  agentOS.vm.network:"public_network", ip:"192.168.1.104"
	  agentOS.vm.provision :shell, path: "bootstrap.sh"
  end
  config.vm.define "PmasterOS" do |masterOS|
	  masterOS.vm.hostname="masterPawanAnsible.qac.local"
	  masterOS.vm.network:"public_network", ip:"192.168.1.103"
	  masterOS.vm.provision :shell, path: "masterbootstrap.sh"
  end
end
